### ISSUE TITLE
incorrect parsing comparison operators not in lowercase

### ISSUE THREAD

**Issue by L2jLiga** [airbus-cert/tree-sitter-powershell#8]
Hello, I've noticed that it does not parse equality operators if they written not in lowercase.
Powershell is case-insensetive so `-like`, `-liKE`, `-Like`, `-LIKE` etc are all the same for it

*error.ps1*:
```powershell
$wordToComplete = "valu"
$IsEqualFlag = ($WordToComplete -Like "--*=*" )
#                                ^--- ERROR
```

*works.ps1*:

```powershell
$wordToComplete = "valu"
$IsEqualFlag = ($WordToComplete -like "--*=*" )
```

**Comment by citronneur** [comment]
Hello, as powershell is case insensitive, we choose to parse only lowercase. So please put the input text as lowercase before.
I know is not the perfect answer but I didn't find a way to manage properly case insensitive with tree-sitter...

**Comment by L2jLiga** [comment]
> Hello, as powershell is case insensitive, we choose to parse only lowercase. So please put the input text as lowercase before.

I think I can't, I [made tree-sitter queries for nvim] and I don't think there's some way to automatically prepare input before parsing.


> I know is not the perfect answer but I didn't find a way to manage properly case insensitive with tree-sitter..

Understand, I guessed that answer will be like that cause I also did not find a way to make it case-insensetive without making regular expressions like
```regex
(F|f)(o|O)(r|R)(c|C)(e|E)
```

[made tree-sitter queries for nvim]: https://github.com/nvim-treesitter/nvim-treesitter/pull/6950

**Comment by citronneur** [comment]
Normally it works !

**Comment by L2jLiga** [comment]
Nice, many thanks!

**Comment by L2jLiga** [comment]
Tested new parser with queries, nothing broken 🎉
