### ISSUE TITLE
Publish to crates.io?

### ISSUE THREAD

**Issue by elijah-potter** [airbus-cert/tree-sitter-powershell#9]
Hey y'all,

Love the work you're doing here. I'm looking to setup Powershell support for a [project of mine](https://github.com/elijah-potter/harper). However, in order to publish packages to `crates.io`, I need all my dependencies to _also_ be on `crates.io`. 

Not to mention that it would make it easier for all other Rust-based projects to consume your work.

It looks like this repository is already setup with Cargo, so it should trivial to get it published. Is there anything I can do to make that happen?

Thanks, Elijah

**Comment by antemasqued** [comment]
Could we have the same for NPM?

**Comment by woodruffw** [comment]
I'd like to second this request -- I also have a project ([zizmor](https://github.com/woodruffw/zizmor)) that could make use of a crates.io distribution of this tree-sitter grammar.

**Comment by woodruffw** [comment]
For those interested: I forked this repo and got the Rust crate working locally, at least for my purposes: https://github.com/woodruffw-forks/tree-sitter-powershell/pull/1

I would greatly prefer to upstream my work here, but worst comes to worst I'll publish `tree-sitter-powershell` from my own fork, which I'd be happy to hand over to the Airbus CERT folks if/when they want it.

**Comment by elijah-potter** [comment]
Do it.

**Comment by woodruffw** [comment]
> Do it.

OK. I'll likely publish the crate tomorrow, and I'll ping back here when I do.

**Comment by citronneur** [comment]
Done ! https://crates.io/search?q=tree-sitter-powershell

**Comment by woodruffw** [comment]
Thanks @citronneur! Is there any chance you could re-generate the parser + Rust bindings to use the latest stable tree-sitter? The current crate uses `~0.22.6`, which `cargo` won't allow in resolutions with any other tree-sitter language that uses `0.23` or newer.

If it would help, I can send a PR doing that regeneration for you -- it requires modifying the repo's metadata slightly, since newer versions of tree-sitter have their own JSON config file.

**Comment by woodruffw** [comment]
For context, this is the conflict that happens when two tree-sitter language crates depend on conflicting native library versions of tree-sitter:

```
    Updating crates.io index
error: failed to select a version for `tree-sitter`.
    ... required by package `tree-sitter-powershell v0.1.0`
    ... which satisfies dependency `tree-sitter-powershell = "^0.1.0"` of package `zizmor v0.6.0 (/Users/william/personal/devel/zizmor)`
versions that meet the requirements `~0.22.6` are: 0.22.6

the package `tree-sitter` links to the native library `tree-sitter`, but it conflicts with a previous package which links to `tree-sitter` as well:
package `tree-sitter v0.23.2`
    ... which satisfies dependency `tree-sitter = "^0.23.2"` of package `zizmor v0.6.0 (/Users/william/personal/devel/zizmor)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the `links = "tree-sitter"` value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `tree-sitter` which could resolve this conflict
```
